# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 10000

on:
  workflow_dispatch:
  schedule:
     - cron: '*/12 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中国电信 签到】'
        run: |
          node Task/10000.js
        env:
          KEY_mobile: ${{ secrets.KEY_MOBILE }}
          KEY_signbody: ${{ secrets.KEY_SIGNBODY }}
